# encoding: utf-8

question_list =[
                #Evaluación al profesor por parte de los estudiantes
                ["Conocimiento","Demuestra dominio en el manejo de los temas que trata"],
                ["Conocimiento","Utiliza los conceptos propios de la asignatura"],
                ["Conocimiento","Responde con claridad a las preguntas formuladas por los estudiantes"],
                ["Conocimiento","Relaciona los contenidos del curso con otras áreas del conocimiento"],
                ["Metología","Mantiene el interés de sus alumnos por los temas de la asignatura"],
                ["Metología","Destaca las ideas principales de los temas"],
                ["Metología","Formula preguntas que inducen al estudiante a razonar"],
                ["Metología","Orienta al estudiante en la búsqueda de respuestas"],
                ["Metología","Es claro al presentar la información, facilitando el aprendizaje al alumno"],
                ["Metología","Recomienda referencias bibliográficas acordes con los temas de estudio"],
                ["Metología","Estimula la participación del estudiante en clase por medio de talleres, grupos de estudio, exposiciones etc."],
                ["Metología","La exposición de los temas es ordenada y responde a la dinámica del curso"],
                ["Metología","Utiliza diversos sistemas educativos distintos a las clase magistral"],
                ["Metología","Fomenta en los estudiantes el uso del vocabulario propio de la asignatura"],
                ["Metología","Mantiene el control de la clase"],
                ["Metología","Cumple con el programa propuesto"],
                ["Metología","Cumple las normas y criterios de evaluación establecidos en el programa y convenios con los estudiantes"],
                ["Metología","Analiza con los estudiantes los resultados de las evaluaciones"],
                ["Metología","Motiva a los estudiantes a realizar las prácticas o talleres y presta asesoría oportuna"],
                ["Metología","Facilita la elaboración de guías apropiadas para el desarrollo del trabajo práctico"],
                ["Metología","Existe correspondencia entre la información teórica y el trabajo práctico"],
                ["Metología","Estimula el análisis y la reflexión sobre el trabajo práctico"],
                ["Relaciones Universitarias","Cumple con los compromisos académicos adquiridos con los estudiantes"],
                ["Relaciones Universitarias","Mantiene una relación respetuosa con los estudiantes"],
                ["Relaciones Universitarias","Motiva a la participación de eventos académicos de la universidad: conferencias, foros, seminarios, etc."],
                ["Relaciones Universitarias","Se interesa en contribuir a la formación integral del estudiantes"],
                ["Relaciones Universitarias","Mantiene una actitud responsable en el trabajo"],
                #Evaluación al profesor por parte del director del departamento
                ["Conocimiento","Demuestra actualización en los conocimientos de su área"],
                ["Conocimiento","Comparte información, experiencias de trabajo etc"],
                ["Conocimiento","Aporta ideas, plantea problemas de investigación relativos a su área"],
                ["Conocimiento","Demuestra interés en utilizar bibliografía actualizada"],
                ["Metología","Orienta la asignatura en función de los objetivos del área y plan de estudios de la carrera"],
                ["Metología","Presenta el programa en una estructura lógica, acorde con los objetivos del mismo"],
                ["Metología","Presenta el programa en una estructura lógica, acorde con los objetivos del mismo"],
                ["Metología","Desarrolla el programa en forma secuencial, y acorde con los objetivos del mismo"],
                ["Metología","La metodología del trabajo corresponde a las características del grupo"],
                ["Metología","La metodología del trabajo corresponde a las características de la temática del área"],
                ["Metología","Se autoevalúa para mejorar su actividad como docente"],
                ["Metología","Actualiza periódicamente sus programas y clases en contenidos, metodología y bibliografía"],
                ["Metología","El sistema evaluativo es coherente con las formas metodológicas empleadas"],
                ["Cumplimiento de labores","Presenta el plan y el informe de actividades"],
                ["Cumplimiento de labores","Es responsable y cumplido en los trabajos que se le asignan"],
                ["Cumplimiento de labores","Cumple con la jornada de trabajo"],
                ["Cumplimiento de labores","Cumple con el horario de clases"],
                ["Cumplimiento de labores","Cumple con las asesorías programadas con los estudiantes"],
                ["Cumplimiento de labores","Se interesa por el trabajo colectivo"],
                ["Cumplimiento de labores","Cumple con las actividades programadas por el Departamento"],
                ["Cumplimiento de labores","Atiende el proceso de presentación de notas"],
                ["Cumplimiento de labores","Cumple con las comisiones que se encargan"],
                ["Relaciones Universitarias","Las relaciones con los compañeros de trabajo son respetuosas y cordiales"],
                ["Relaciones Universitarias","Su relación con los estudiantes es cordial y respetuosa"],
                ["Relaciones Universitarias","Comunica oportunamente a las personas que corresponde, para suspender o cambiar actividades programadas"],
                ["Relaciones Universitarias","Analiza y discute con respeto las ideas de los demás"],
                #Evaluación al profesor por parte del decano
                ["Cumplimiento","Asiste puntualmente a las reuniones programadas por la Facultad"],
                ["Cumplimiento","Permanece en las reuniones programadas por la Facultad"],
                ["Cumplimiento","Presenta los informes solicitados por la Facultad"],
                ["Cumplimiento","Cumple con los trabajos asignados por la Facultad"],
                ["Cumplimiento","Participa activamente en las actividades programadas por la Facultad"],
                ["Cumplimiento","Conserva los bienes, documentos y materiales de la Universidad"],
                ["Cumplimiento","Cumple con los compromisos de trabajos adquiridos con la Facultad y/o la Universidad"],
                ["Relaciones Universitarias","Tiene en cuenta los canales de comunicación existentes"],
                ["Relaciones Universitarias","Tiene un trato respetuoso con sus compañeros"],
                ["Relaciones Universitarias","Observa las normas inherentes a la ética de su profesión"],
                ["Relaciones Universitarias","Contribuye a la realización de actividades complementarias a la labor académica"],
                ["Relaciones Universitarias","Colabora en la realización de eventos especiales programados por la Facultad"],
                ["Relaciones Universitarias","Contribuye al desarrollo de las relaciones interinstitucionales de la Facultad"],
                ["Relaciones Universitarias","Mantiene una actitud respetuosa frente a la institución"],
               ] 

question_list.each do |aspect, item|
  Question.create( aspect: aspect, item: item )
end


