#Evaluación al profesor por parte de los estudiantes

Question.create(item: "Demuestra dominio en el manejo de los temas que trata", aspect: "Conocimiento")
Question.create(item: "Utiliza los conceptos propios de la asignatura", aspect: "Conocimiento")
Question.create(item: "Responde con claridad a las preguntas formuladas por los estudiantes", aspect: "Conocimiento")
Question.create(item: "Relaciona los contenidos del curso con otras áreas del conocimiento", aspect: "Conocimiento")

Question.create(item: "Mantiene el interés de sus alumnos por los temas de la asignatura", aspect: "Metología")
Question.create(item: "Destaca las ideas principales de los temas", aspect: "Metología")
Question.create(item: "Formula preguntas que inducen al estudiante a razonar", aspect: "Metología")
Question.create(item: "Orienta al estudiante en la búsqueda de respuestas", aspect: "Metología")
Question.create(item: "Es claro al presentar la información, facilitando el aprendizaje al alumno", aspect: "Metología")
Question.create(item: "Recomienda referencias bibliográficas acordes con los temas de estudio", aspect: "Metología")
Question.create(item: "Estimula la participación del estudiante en clase por medio de talleres, grupos de estudio, exposiciones etc.", aspect: "Metología")
Question.create(item: "La exposición de los temas es ordenada y responde a la dinámica del curso", aspect: "Metología")
Question.create(item: "Utiliza diversos sistemas educativos distintos a las clase magistral", aspect: "Metología")
Question.create(item: "Fomenta en los estudiantes el uso del vocabulario propio de la asignatura", aspect: "Metología")
Question.create(item: "Mantiene el control de la clase", aspect: "Metología")
Question.create(item: "Cumple con el programa propuesto", aspect: "Metología")
Question.create(item: "Cumple las normas y criterios de evaluación establecidos en el programa y convenios con los estudiantes", aspect: "Metología")
Question.create(item: "Analiza con los estudiantes los resultados de las evaluaciones", aspect: "Metología")
Question.create(item: "Motiva a los estudiantes a realizar las prácticas o talleres y presta asesoría oportuna", aspect: "Metología")
Question.create(item: "Facilita la elaboración de guías apropiadas para el desarrollo del trabajo práctico", aspect: "Metología")
Question.create(item: "Existe correspondencia entre la información teórica y el trabajo práctico", aspect: "Metología")
Question.create(item: "Estimula el análisis y la reflexión sobre el trabajo práctico", aspect: "Metología")

Question.create(item: "Cumple con los compromisos académicos adquiridos con los estudiantes", aspect: "Relaciones Universitarias")
Question.create(item: "Mantiene una relación respetuosa con los estudiantes", aspect: "Relaciones Universitarias")
Question.create(item: "Motiva a la participación de eventos académicos de la universidad: conferencias, foros, seminarios, etc.", aspect: "Relaciones Universitarias")
Question.create(item: "Se interesa en contribuir a la formación integral del estudiantes", aspect: "Relaciones Universitarias")
Question.create(item: "Mantiene una actitud responsable en el trabajo", aspect: "Relaciones Universitarias")

#Evaluación al profesor por parte del director del departamento

Question.create(item: "Demuestra actualización en los conocimientos de su área", aspect: "Conocimiento")
Question.create(item: "Comparte información, experiencias de trabajo etc", aspect: "Conocimiento")
Question.create(item: "Aporta ideas, plantea problemas de investigación relativos a su área", aspect: "Conocimiento")
Question.create(item: "Demuestra interés en utilizar bibliografía actualizada", aspect: "Conocimiento")

Question.create(item: "Orienta la asignatura en función de los objetivos del área y plan de estudios de la carrera", aspect: "Metología")
Question.create(item: "Presenta el programa en una estructura lógica, acorde con los objetivos del mismo", aspect: "Metología")
Question.create(item: "Presenta el programa en una estructura lógica, acorde con los objetivos del mismo", aspect: "Metología")
Question.create(item: "Desarrolla el programa en forma secuencial, y acorde con los objetivos del mismo", aspect: "Metología")
Question.create(item: "La metodología del trabajo corresponde a las características del grupo", aspect: "Metología")
Question.create(item: "La metodología del trabajo corresponde a las características de la temática del área", aspect: "Metología")
Question.create(item: "Se autoevalúa para mejorar su actividad como docente", aspect: "Metología")
Question.create(item: "Actualiza periódicamente sus programas y clases en contenidos, metodología y bibliografía", aspect: "Metología")
Question.create(item: "El sistema evaluativo es coherente con las formas metodológicas empleadas", aspect: "Metología")

Question.create(item: "Presenta el plan y el informe de actividades", aspect: "Cumplimiento de labores")
Question.create(item: "Es responsable y cumplido en los trabajos que se le asignan", aspect: "Cumplimiento de labores")
Question.create(item: "Cumple con la jornada de trabajo", aspect: "Cumplimiento de labores")
Question.create(item: "Cumple con el horario de clases", aspect: "Cumplimiento de labores")
Question.create(item: "Cumple con las asesorías programadas con los estudiantes", aspect: "Cumplimiento de labores")
Question.create(item: "Se interesa por el trabajo colectivo", aspect: "Cumplimiento de labores")
Question.create(item: "Cumple con las actividades programadas por el Departamento", aspect: "Cumplimiento de labores")
Question.create(item: "Atiende el proceso de presentación de notas", aspect: "Cumplimiento de labores")
Question.create(item: "Cumple con las comisiones que se encargan", aspect: "Cumplimiento de labores")

Question.create(item: "Las relaciones con los compañeros de trabajo son respetuosas y cordiales", aspect: "Relaciones Universitarias")
Question.create(item: "Su relación con los estudiantes es cordial y respetuosa", aspect: "Relaciones Universitarias")
Question.create(item: "Comunica oportunamente a las personas que corresponde, para suspender o cambiar actividades programadas", aspect: "Relaciones Universitarias")
Question.create(item: "Analiza y discute con respeto las ideas de los demás", aspect: "Relaciones Universitarias")

#Evaluación al profesor por parte del decano

Question.create(item: "Asiste puntualmente a las reuniones programadas por la Facultad", aspect: "Cumplimiento")
Question.create(item: "Permanece en las reuniones programadas por la Facultad", aspect: "Cumplimiento")
Question.create(item: "Presenta los informes solicitados por la Facultad", aspect: "Cumplimiento")
Question.create(item: "Cumple con los trabajos asignados por la Facultad", aspect: "Cumplimiento")
Question.create(item: "Participa activamente en las actividades programadas por la Facultad", aspect: "Cumplimiento")
Question.create(item: "Conserva los bienes, documentos y materiales de la Universidad", aspect: "Cumplimiento")
Question.create(item: "Cumple con los compromisos de trabajos adquiridos con la Facultad y/o la Universidad", aspect: "Cumplimiento")

Question.create(item: "Tiene en cuenta los canales de comunicación existentes", aspect: "Relaciones Universitarias")
Question.create(item: "Tiene un trato respetuoso con sus compañeros", aspect: "Relaciones Universitarias")
Question.create(item: "Observa las normas inherentes a la ética de su profesión", aspect: "Relaciones Universitarias")
Question.create(item: "Contribuye a la realización de actividades complementarias a la labor académica", aspect: "Relaciones Universitarias")
Question.create(item: "Colabora en la realización de eventos especiales programados por la Facultad", aspect: "Relaciones Universitarias")
Question.create(item: "Contribuye al desarrollo de las relaciones interinstitucionales de la Facultad", aspect: "Relaciones Universitarias")
Question.create(item: "Mantiene una actitud respetuosa frente a la institución", aspect: "Relaciones Universitarias")